---
IslandSizeX: 100
IslandSizeY: 20
residentsProperties:
  "Wolf" : 50
  "Bear" : 0
  "Fox" : 0
  "Boa" : 0
  "Eagle" : 0

  "Deer" : 0
  "Horse" : 0
  "Duck" : 0
  "Rabbit" : 300
  "Goat" : 0
  "Mouse": 0
  "Caterpillar": 0
  "Buffalo" : 0
  "Boar": 0
  "Sheep": 0

  "Grass" : 500


