---
IslandSize: 100
residentsProperties:
  "Wolf" : 20
  "Bear" : 0
  "Fox" : 0
  "Boa" : 0
  "Eagle" : 0

  "Deer" : 1
  "Horse" : 0
  "Duck" : 0
  "Rabbit" : 100
  "Goat" : 0
  "Mouse": 0
  "Caterpillar": 0
  "Buffalo" : 0
  "Boar": 0
  "Sheep": 0

  "Grass" : 50


