---
IslandSizeX: 100
IslandSizeY: 20
residentsProperties:
  "Wolf" : 150
  "Bear" : 150
  "Fox" : 150
  "Boa" : 150
  "Eagle" : 150

  "Deer" : 150
  "Horse" : 150
  "Duck" : 150
  "Rabbit" : 150
  "Goat" : 150
  "Mouse": 150
  "Caterpillar": 150
  "Buffalo" : 150
  "Boar": 150
  "Sheep": 150

  "Grass" : 500


